## YAML Template.
---
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
    org.springframework.security: TRACE

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:

  port: 8901
spring:
  application:
    name: authservice
    

      
security:
#  basic:
#    enabled: false
  user:
    name: admin
    password: admin
  oauth2:
    client:
      client-id: clientId
      client-secret: secretcode
  