## YAML Template.
---
server:  
  port: ${PORT:8765}

spring:  
  application:
    name: zuul-gateway
  
logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
      
zuul:
  routes:
    
    authservice:
      path: /oauth/**
      sensitiveHeaders: 
      serviceId: authservice
    
    employee:
      path: /emp/**
      sensitiveHeaders: 
      serviceId: empservice
    login:
      path: /log/**
      sensitiveHeaders: 
      serviceId: loginservice
  sensitiveHeaders: Cookie,Set-Cookie     
  
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  user:
    name: admin
    password: admin
  oauth2:
    client:
      accessTokenUri: http://localhost:8765/oauth/oauth/token
      userAuthorizationUri: http://localhost:8765/oauth/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:8765/oauth/user/
      preferTokenInfo: true  
  sessions: ALWAYS 

proxy:
  auth:
    routes:
      employee: oauth2
      login: oauth2