## YAML Template.
---
spring:
    application:
        name: empservice
    profiles:
        active:
            default
    cloud:
        config:
            enabled: true
eureka:
    instances:
        preferIpAdress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
                 